services:
  db:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: booksdb
    volumes:
      - db-data:/var/lib/postgresql/data

  api:
    build: ./api
    restart: always
    ports:
      - "3001:3001"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/booksdb
    volumes:
      - ./api:/app
    command: sh -c "npx prisma db push && npm run dev"

  frontend:
    build: ./frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - api
    volumes:
      - ./frontend:/app
    command: npm run dev -- --host

volumes:
  db-data:
